-- AlterTable
ALTER TABLE `notification` ADD COLUMN `image` VARCHAR(191) NULL,
    ADD COLUMN `scheduledTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `type` ENUM('COLLEGE', 'UNIVERSITY', 'INDIVIDUAL', 'BATCH', 'DEPARTMENT') NOT NULL DEFAULT 'COLLEGE';
